-- Create servicios_domesticos table
CREATE TABLE public.servicios_domesticos (
  id BIGSERIAL PRIMARY KEY,
  especialista TEXT NOT NULL,
  categoria TEXT NOT NULL,
  actividad TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.servicios_domesticos ENABLE ROW LEVEL SECURITY;

-- Allow anyone to read services (public data)
CREATE POLICY "Anyone can read servicios_domesticos"
  ON public.servicios_domesticos
  FOR SELECT
  USING (true);

-- Insert all the services data
INSERT INTO public.servicios_domesticos (especialista, categoria, actividad) VALUES
('Jardinero', 'Jardinería', 'Cortar pasto'),
('Jardinero', 'Jardinería', 'Plantar pasto'),
('Jardinero', 'Jardinería', 'Plantar flores o árboles'),
('Jardinero', 'Jardinería', 'Podar árboles'),
('Jardinero', 'Jardinería', 'Mantenimiento de jardín'),
('Jardinero', 'Jardinería', 'Instalar sistema de riego'),
('Jardinero', 'Jardinería', 'Fumigar plantas'),
('Jardinero', 'Jardinería', 'Retiro de maleza'),
('Jardinero', 'Jardinería', 'Diseño de jardín'),
('Plomero', 'Plomería', 'Destapar baño o fregadero'),
('Plomero', 'Plomería', 'Reparar fugas'),
('Plomero', 'Plomería', 'Instalar lavabo o fregadero'),
('Plomero', 'Plomería', 'Cambiar mezcladora o regadera'),
('Plomero', 'Plomería', 'Instalar calentador o tinaco'),
('Plomero', 'Plomería', 'Mantenimiento de drenaje'),
('Plomero', 'Plomería', 'Detectar fugas'),
('Plomero', 'Plomería', 'Instalar bomba de agua'),
('Electricista', 'Electricidad', 'Instalar contacto o apagador'),
('Electricista', 'Electricidad', 'Cambiar foco o lámpara'),
('Electricista', 'Electricidad', 'Instalar ventilador o extractor'),
('Electricista', 'Electricidad', 'Reparar corto circuito'),
('Electricista', 'Electricidad', 'Instalar timbre o interfono'),
('Electricista', 'Electricidad', 'Mantenimiento eléctrico menor'),
('Electricista', 'Electricidad', 'Revisión de fusibles o pastillas'),
('Electricista', 'Electricidad', 'Instalación de sensores'),
('Albañil', 'Albañilería', 'Construir o reparar muro'),
('Albañil', 'Albañilería', 'Colocar azulejo o piso'),
('Albañil', 'Albañilería', 'Resanar'),
('Albañil', 'Albañilería', 'Aplanar muros'),
('Albañil', 'Albañilería', 'Construir barda'),
('Albañil', 'Albañilería', 'Reparar techo o losa'),
('Albañil', 'Albañilería', 'Colar piso'),
('Albañil', 'Albañilería', 'Enjarre o repellado'),
('Albañil', 'Albañilería', 'Demolición menor'),
('Pintor', 'Pintura', 'Pintar interiores o exteriores'),
('Pintor', 'Pintura', 'Pintar fachada'),
('Pintor', 'Pintura', 'Impermeabilizar'),
('Pintor', 'Pintura', 'Aplicar sellador o esmalte'),
('Pintor', 'Pintura', 'Retirar pintura vieja'),
('Pintor', 'Pintura', 'Pintar rejas o barandales'),
('Pintor', 'Pintura', 'Pintura decorativa'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpieza general de casa'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpieza profunda de baño o cocina'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpiar vidrios'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpiar patios o terrazas'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Lavado de alfombras'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpieza de oficinas'),
('Limpiadora / Personal de limpieza', 'Limpieza', 'Limpieza posterior a obra'),
('Lavador de autos', 'Lavado de autos', 'Lavado exterior'),
('Lavador de autos', 'Lavado de autos', 'Lavado interior'),
('Lavador de autos', 'Lavado de autos', 'Aspirado'),
('Lavador de autos', 'Lavado de autos', 'Lavado de tapicería'),
('Lavador de autos', 'Lavado de autos', 'Encerado'),
('Lavador de autos', 'Lavado de autos', 'Pulido'),
('Lavador de autos', 'Lavado de autos', 'Limpieza de motor'),
('Técnico de albercas', 'Albercas', 'Limpieza regular'),
('Técnico de albercas', 'Albercas', 'Limpieza profunda y vaciado'),
('Técnico de albercas', 'Albercas', 'Mantenimiento de filtros'),
('Técnico de albercas', 'Albercas', 'Control de pH y químicos'),
('Técnico de albercas', 'Albercas', 'Reparación de fugas'),
('Técnico de albercas', 'Albercas', 'Revisión de bomba'),
('Técnico de albercas', 'Albercas', 'Instalación de equipos'),
('Carpintero', 'Carpintería', 'Reparar muebles'),
('Carpintero', 'Carpintería', 'Fabricar puertas o clósets'),
('Carpintero', 'Carpintería', 'Instalar molduras o zoclos'),
('Carpintero', 'Carpintería', 'Reparar sillas o mesas'),
('Carpintero', 'Carpintería', 'Hacer muebles a medida'),
('Carpintero', 'Carpintería', 'Instalar cocinas integrales'),
('Carpintero', 'Carpintería', 'Lijar y barnizar'),
('Herrero', 'Herrería', 'Fabricar e instalar puertas o rejas'),
('Herrero', 'Herrería', 'Soldadura general'),
('Herrero', 'Herrería', 'Reparar portones'),
('Herrero', 'Herrería', 'Estructuras metálicas'),
('Herrero', 'Herrería', 'Barandales'),
('Herrero', 'Herrería', 'Techos ligeros'),
('Herrero', 'Herrería', 'Mantenimiento de herrería'),
('Vidriero', 'Vidriería', 'Cortar e instalar vidrios'),
('Vidriero', 'Vidriería', 'Reparación de ventanas'),
('Vidriero', 'Vidriería', 'Colocación de espejos'),
('Vidriero', 'Vidriería', 'Instalación de canceles'),
('Vidriero', 'Vidriería', 'Cristales templados'),
('Vidriero', 'Vidriería', 'Sellado de ventanas'),
('Cerrajero', 'Cerrajería', 'Abrir cerraduras'),
('Cerrajero', 'Cerrajería', 'Duplicar llaves'),
('Cerrajero', 'Cerrajería', 'Cambiar chapa'),
('Cerrajero', 'Cerrajería', 'Instalar cerraduras digitales'),
('Cerrajero', 'Cerrajería', 'Reparación de puertas de metal o aluminio'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Mantenimiento preventivo'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Carga de gas'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Limpieza de filtros'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Instalación de minisplit'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Reparación de compresores'),
('Técnico en refrigeración / aire acondicionado', 'Climatización', 'Instalación eléctrica para A/C'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Reparar lavadora'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Refrigerador'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Estufa'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Microondas'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Licuadora'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Plancha'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Aspiradora'),
('Técnico en electrodomésticos', 'Reparación de electrodomésticos', 'Instalación de aparatos nuevos'),
('Técnico en CCTV / Seguridad', 'Seguridad y cámaras', 'Instalación de cámaras de seguridad'),
('Técnico en CCTV / Seguridad', 'Seguridad y cámaras', 'Mantenimiento de CCTV'),
('Técnico en CCTV / Seguridad', 'Seguridad y cámaras', 'Instalación de alarmas o sensores'),
('Técnico en CCTV / Seguridad', 'Seguridad y cámaras', 'Configuración de DVR/NVR'),
('Técnico en CCTV / Seguridad', 'Seguridad y cámaras', 'Reparación de cableado'),
('Fumigador', 'Control de plagas', 'Fumigación contra cucarachas'),
('Fumigador', 'Control de plagas', 'Hormigas'),
('Fumigador', 'Control de plagas', 'Termitas'),
('Fumigador', 'Control de plagas', 'Roedores'),
('Fumigador', 'Control de plagas', 'Desinfección general'),
('Fumigador', 'Control de plagas', 'Control de mosquitos'),
('Fumigador', 'Control de plagas', 'Mantenimiento programado'),
('Tapicero', 'Tapicería', 'Tapizado de muebles'),
('Tapicero', 'Tapicería', 'Reparación de asientos'),
('Tapicero', 'Tapicería', 'Cambio de tela o espuma'),
('Tapicero', 'Tapicería', 'Limpieza de tapicería'),
('Tapicero', 'Tapicería', 'Restauración de sillones o sillas'),
('Cristalero automotriz', 'Autos / Cristales', 'Cambio de parabrisas'),
('Cristalero automotriz', 'Autos / Cristales', 'Reparación de vidrios automotrices'),
('Cristalero automotriz', 'Autos / Cristales', 'Sellado de filtraciones'),
('Cristalero automotriz', 'Autos / Cristales', 'Polarizado'),
('Fontanero industrial', 'Mantenimiento empresarial', 'Instalación de tuberías industriales'),
('Fontanero industrial', 'Mantenimiento empresarial', 'Mantenimiento de drenajes'),
('Fontanero industrial', 'Mantenimiento empresarial', 'Instalación de bombas de presión'),
('Fontanero industrial', 'Mantenimiento empresarial', 'Revisión de válvulas y conexiones'),
('Mecánico', 'Mecánica automotriz', 'Cambio de aceite'),
('Mecánico', 'Mecánica automotriz', 'Revisión de frenos'),
('Mecánico', 'Mecánica automotriz', 'Afinación'),
('Mecánico', 'Mecánica automotriz', 'Suspensión'),
('Mecánico', 'Mecánica automotriz', 'Alineación'),
('Mecánico', 'Mecánica automotriz', 'Diagnóstico eléctrico'),
('Mecánico', 'Mecánica automotriz', 'Cambio de batería'),
('Técnico en computadoras', 'Electrónica / TI', 'Reparación de laptops o PC'),
('Técnico en computadoras', 'Electrónica / TI', 'Instalación de software'),
('Técnico en computadoras', 'Electrónica / TI', 'Limpieza interna'),
('Técnico en computadoras', 'Electrónica / TI', 'Cambio de piezas'),
('Técnico en computadoras', 'Electrónica / TI', 'Instalación de red doméstica'),
('Soldador', 'Soldadura', 'Soldadura eléctrica'),
('Soldador', 'Soldadura', 'Soldadura autógena o MIG'),
('Soldador', 'Soldadura', 'Reparación de estructuras'),
('Soldador', 'Soldadura', 'Fabricación de barandales o soportes'),
('Soldador', 'Soldadura', 'Soldadura en campo'),
('Impermeabilizador', 'Impermeabilización', 'Aplicar impermeabilizante'),
('Impermeabilizador', 'Impermeabilización', 'Sellar grietas'),
('Impermeabilizador', 'Impermeabilización', 'Revisar goteras'),
('Impermeabilizador', 'Impermeabilización', 'Mantenimiento preventivo de azotea'),
('Yesero', 'Yesería', 'Aplicar yeso en muros o techos'),
('Yesero', 'Yesería', 'Resanar'),
('Yesero', 'Yesería', 'Molduras de yeso'),
('Yesero', 'Yesería', 'Nivelado de paredes'),
('Cristalero', 'Vidriería / Aluminio', 'Instalación de canceles'),
('Cristalero', 'Vidriería / Aluminio', 'Ventanas'),
('Cristalero', 'Vidriería / Aluminio', 'Puertas de vidrio o aluminio'),
('Cristalero', 'Vidriería / Aluminio', 'Mantenimiento de marcos'),
('Cristalero', 'Vidriería / Aluminio', 'Colocación de vidrios templados'),
('Montacarguista / Técnico industrial', 'Mantenimiento industrial', 'Revisión de montacargas'),
('Montacarguista / Técnico industrial', 'Mantenimiento industrial', 'Mantenimiento de maquinaria'),
('Montacarguista / Técnico industrial', 'Mantenimiento industrial', 'Lubricación y ajustes'),
('Montacarguista / Técnico industrial', 'Mantenimiento industrial', 'Inspección de seguridad');