-- Clear existing data from servicios_domesticos
DELETE FROM servicios_domesticos;

-- Insert new catalog data
INSERT INTO servicios_domesticos (especialista, actividad, categoria) VALUES
('Jardinero', 'Jardinería', 'Jardinería'),
('Paisajista', 'Diseño de jardines', 'Jardinería'),
('Podador de árboles', 'Poda', 'Jardinería'),
('Técnico en riego', 'Sistemas de riego', 'Jardinería'),
('Plomero', 'Plomería', 'Servicios del hogar'),
('Plomero industrial', 'Plomería industrial', 'Servicios industriales'),
('Electricista', 'Electricidad residencial', 'Servicios del hogar'),
('Electricista industrial', 'Electricidad industrial', 'Servicios industriales'),
('Albañil', 'Albañilería', 'Construcción'),
('Yesero', 'Yesería', 'Construcción'),
('Pintor', 'Pintura residencial', 'Pintura'),
('Impermeabilizador', 'Impermeabilización', 'Pintura'),
('Carpintero', 'Carpintería', 'Carpintería'),
('Ebanista', 'Carpintería fina', 'Carpintería'),
('Herrero', 'Herrería', 'Metal / Construcción'),
('Soldador', 'Soldadura', 'Metal / Construcción'),
('Vidriero', 'Vidriería', 'Vidriería'),
('Aluminiero', 'Aluminio y cancelería', 'Vidriería'),
('Cerrajero', 'Cerrajería', 'Seguridad'),
('Técnico en aire acondicionado', 'A/C y climatización', 'Climatización'),
('Técnico en refrigeración', 'Refrigeración', 'Climatización'),
('Limpieza general', 'Limpieza residencial', 'Limpieza'),
('Limpieza profunda', 'Limpieza especializada', 'Limpieza'),
('Limpiador de tapicería', 'Limpieza de muebles', 'Limpieza'),
('Limpiador de alfombras', 'Limpieza de alfombras', 'Limpieza'),
('Fumigador', 'Control de plagas', 'Fumigación'),
('Desinfectador', 'Sanitización', 'Fumigación'),
('Lavador de autos', 'Lavado automotriz', 'Automotriz'),
('Detallador automotriz', 'Detailing', 'Automotriz'),
('Mecánico automotriz', 'Mecánica', 'Automotriz'),
('Electricista automotriz', 'Electricidad automotriz', 'Automotriz'),
('Cristalero automotriz', 'Cristales para autos', 'Automotriz'),
('Mudancero', 'Mudanzas', 'Transporte'),
('Chofer', 'Transporte privado', 'Transporte'),
('Cargador', 'Carga y descarga', 'Transporte'),
('Tapicero', 'Tapicería', 'Hogar'),
('Tapicero automotriz', 'Tapicería automotriz', 'Automotriz'),
('Decorador de interiores', 'Decoración', 'Decoración'),
('Diseñador de interiores', 'Diseño de interiores', 'Decoración'),
('Técnico CCTV', 'Sistemas de cámaras', 'Seguridad'),
('Técnico en alarmas', 'Alarmas y sensores', 'Seguridad'),
('Guardia de seguridad', 'Seguridad privada', 'Seguridad'),
('Técnico en computadoras', 'Reparación de computadoras', 'Tecnología'),
('Técnico en celulares', 'Reparación de celulares', 'Tecnología'),
('Técnico en redes', 'Redes e internet', 'Tecnología'),
('Programador', 'Desarrollo de software', 'Tecnología'),
('Diseñador gráfico', 'Diseño gráfico', 'Creativo'),
('Community Manager', 'Gestión de redes', 'Creativo'),
('Fotógrafo', 'Fotografía', 'Creativo'),
('Videógrafo', 'Video', 'Creativo'),
('Chef', 'Cocina a domicilio', 'Gastronomía'),
('Cocinero', 'Cocina general', 'Gastronomía'),
('Repostero', 'Repostería', 'Gastronomía'),
('Mesero', 'Servicio para eventos', 'Eventos'),
('Bartender', 'Barra y coctelería', 'Eventos'),
('DJ', 'Música para eventos', 'Eventos'),
('Organizador de eventos', 'Organización de eventos', 'Eventos'),
('Profesor de matemáticas', 'Matemáticas', 'Educación'),
('Profesor de inglés', 'Inglés', 'Educación'),
('Profesor de música', 'Música', 'Educación'),
('Asesor educativo', 'Regularización escolar', 'Educación'),
('Entrenador personal', 'Fitness', 'Salud y deporte'),
('Instructor de yoga', 'Yoga', 'Salud y deporte'),
('Instructor de baile', 'Baile', 'Salud y deporte'),
('Nutriólogo', 'Nutrición', 'Salud'),
('Psicólogo', 'Psicología', 'Salud'),
('Fisioterapeuta', 'Fisioterapia', 'Salud'),
('Masajista', 'Masajes', 'Salud'),
('Enfermero', 'Enfermería', 'Salud'),
('Cuidador de adultos mayores', 'Cuidado de adultos', 'Cuidado personal'),
('Niñera', 'Cuidado infantil', 'Cuidado personal'),
('Estilista', 'Belleza', 'Belleza'),
('Barber', 'Barbería', 'Belleza'),
('Manicurista', 'Uñas', 'Belleza'),
('Maquillista', 'Maquillaje', 'Belleza'),
('Técnico en paneles solares', 'Energía solar', 'Energía'),
('Técnico en bombas de agua', 'Bombas y presión', 'Mantenimiento'),
('Técnico de albercas', 'Mantenimiento de albercas', 'Albercas'),
('Limpiador de albercas', 'Limpieza de albercas', 'Albercas'),
('Soldador industrial', 'Soldadura industrial', 'Industrial'),
('Técnico de mantenimiento general', 'Multiservicios', 'Mantenimiento'),
('Auxiliar de limpieza industrial', 'Limpieza industrial', 'Limpieza'),
('Topógrafo', 'Topografía', 'Construcción'),
('Arquitecto', 'Arquitectura', 'Construcción'),
('Ingeniero civil', 'Ingeniería civil', 'Construcción'),
('Abogado', 'Servicios legales', 'Servicios profesionales'),
('Contador', 'Contabilidad', 'Servicios profesionales'),
('Asesor financiero', 'Finanzas', 'Servicios profesionales'),
('Traductor', 'Traducción', 'Servicios profesionales');

-- Create indexes for better search performance
CREATE INDEX IF NOT EXISTS idx_servicios_especialista ON servicios_domesticos(especialista);
CREATE INDEX IF NOT EXISTS idx_servicios_actividad ON servicios_domesticos(actividad);
CREATE INDEX IF NOT EXISTS idx_servicios_categoria ON servicios_domesticos(categoria);